In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

bn = tf.keras.layers.BatchNormalization(momentum=0.5,
    beta_initializer='zeros', gamma_initializer='ones',
    moving_mean_initializer='ones', moving_variance_initializer='ones',
    fused=False)
# Training Step 0 (skip the real scale/offset update)
x0 = tf.random.uniform((2,1,2,3))
print("x(step0):", x0.numpy())

y0 = bn(x0, training=True)
print("moving_mean(step0): ", bn.moving_mean.numpy())
print("moving_var(step0): ", bn.moving_variance.numpy())
print("y(step0):", y0.numpy())

x(step0): [[[[0.31455445 0.13217592 0.40529144]
   [0.7373042  0.20413649 0.15066624]]]


 [[[0.05149686 0.4641961  0.40172493]
   [0.53219056 0.28925872 0.24617374]]]]
moving_mean(step0):  [0.7044433  0.63622093 0.65048206]
moving_var(step0):  [0.532461   0.5076741  0.50582856]
y(step0): [[[[-0.36740422 -1.0970279   0.92732334]
   [ 1.2791202  -0.53422    -1.3359364 ]]]


 [[[-1.3919601   1.4997215   0.895622  ]
   [ 0.48024416  0.131526   -0.4870093 ]]]]
